---

- hosts: all
  
  tasks:
    - name: Install aptitude
      become: true
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Install required system packages
      become: true
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Install python required packages
      become: true
      apt:
        pkg:
          - make 
          - build-essential
          - libssl-dev 
          - zlib1g-dev
          - libbz2-dev     
          - libreadline-dev
          - libsqlite3-dev
          - wget
          - curl
          - llvm
          - libncursesw5-dev 
          - xz-utils
          - tk-dev
          - libxml2-dev
          - libxmlsec1-dev
          - libffi-dev
          - liblzma-dev
        state: latest
        update_cache: true

    - name: clone pyenv project
      shell:
        cmd: "curl https://pyenv.run | bash"

    - name: Init Env
      shell: |
        echo 'export PATH="$HOME/.pyenv/bin:$PATH"' >> ~/.bashrc
        echo 'eval "$(pyenv init -)"' >> .bashrc
        echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.bashrc
    
    - name: Install python 3.9.0 for awx
      shell:
        cmd: "pyenv install -v 3.9.0"

         